# Generated by Django 2.1.7 on 2019-03-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout', models.CharField(max_length=10000)),
            ],
        ),
    ]
